solution of tasks 1_(2 - 5)
js-tasks-ru/jsbasic-20221028_del-ry4me pull request #2
Opened 2022-10-31 18:47 UTC by ArtemViktorovitch

2022-10-31 18:48 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-11-01 17:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-11-03 08:06 UTC, koalex requested changes
Исправить замечание 2-3

2022-11-03 08:06 UTC, koalex commented on 1-module/4-task/index.js
> +  if (strInLowerCase.includes("1xbet") || strInLowerCase.includes("xxx")) {
Можно так: `return strInLowerCase.includes("1xbet") || strInLowerCase.includes("xxx");`

2022-11-03 08:06 UTC, koalex commented on 2-module/3-task/index.js
> +    calculator.a = a;
Несмотря на то что тесты отрабатывают тут надо исправить. Вместо `calculator` должно быть `this`

2022-11-03 11:16 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-11-04 07:08 UTC, koalex approved these changes

2022-11-04 07:09 UTC, merged